version: "3.9"

services:
  white-label-builder:
    image: tensorflow/serving
    ports:
      - 8501:8501
    environment:
      MODEL_NAME: model
    volumes:
      - './models/model:/models/model'

